Some proposal after functional testing
guewen/queue pull request #2
Opened 2016-11-25 08:43 UTC by adrienpeiffer

Releted to https://github.com/OCA/queue/pull/1

2016-11-25 09:00 UTC, guewen requested changes
Thanks for the test and changes!

Out of curiosity, what was the need for the new cursor?

I made some comments, mostly:

* the new cr stuff can be factored in a single context manager, besides, it must be closed in a `finally` to be sure it is closed properly in any case
* I'm a bit surprised by the issues you had with the `im_class` so I would be glad to have some details

2016-11-25 09:00 UTC, guewen commented on queue_job/models/queue_job.py
> +    for key, value in method.func_globals.iteritems():
Couldn't you use `_is_model_method` instead of iterating over the globals?

2016-11-25 09:00 UTC, guewen commented on queue_job/job.py
> +                cr.close()
The close should be in a `finally`.
You could factor this out with a context manager

```python

@contextmanager
def use_new_env(self, env):
    cr = registry(env).cursor()
    new_env = env(cr=cr)
    try:
        yield new_env
    except:
        cr.rollback()
        raise
    else:
        cr.commit()
    finally:
        cr.close()

2016-11-25 09:00 UTC, guewen commented on queue_job/job.py
> +                cr.close()
The close should be in a finally.

2016-11-25 09:00 UTC, guewen commented on queue_job/job.py
> +            cr.close()
The close should be in a finally.

2016-11-25 09:00 UTC, guewen commented on queue_job/models/queue_job.py
> +    for key, value in method.func_globals.iteritems():
I saw your commit's comment "im_class seems not accessible". What is the type of `method` in your use case?

2016-11-28 06:54 UTC, adrienpeiffer commented on queue_job/models/queue_job.py
> +    for key, value in method.func_globals.iteritems():
As your exemple, this is a simple method defined in a class like 

```
class TestQueueJob(models.Model):

    _name = 'test.queue.job'

    name = fields.Char(required=True)

    @job
    def do_job(self):
        return
```

And with this example and your code, the server fails during the initialization.

2016-11-28 07:05 UTC, adrienpeiffer commented
Hi @guewen,

Thanks for comments.
About the cursor, [Here](https://github.com/guewen/queue/pull/2/files#diff-c61ef52f6c5b2184f39e2ae518fe7e77L124) you tried to commit the current transaction just before a raise. However, at this step, we should rollback the transaction by raising an exception. So for me the first step was to remove the commit to rollback the transaction properly. But, after removing this one, the storing of the job was also canceled. So I added the possibility to store a job with a new cursor to allow to store the job without rollback on the current transaction.

2016-11-29 07:58 UTC, guewen commented on queue_job/models/queue_job.py
> +    for key, value in method.func_globals.iteritems():
You are right, the function is not yet bound to the class at this point. Your check does not seem to work better, in my case, the class is not in the globals of the function. It seems we can only check that at runtime when the delay is called.

2016-11-29 08:02 UTC, guewen commented on queue_job/job.py
> +    func.delay = delay_func
could you replace `delay_func` by `delay_from_model` and remove the initialization of `delay_func` above?

2016-11-29 08:16 UTC, guewen commented on queue_job/models/queue_job.py
> +    for key, value in method.func_globals.iteritems():
Indeed. Looping over the `func_globals` bothers me but I don't see another way.

2016-12-02 10:49 UTC, adrienpeiffer commented
Hi @guewen,

In my last commit, I improved the way to store a job after exception according OCA guidelines.

2016-12-02 11:38 UTC, guewen approved these changes

2016-12-02 11:39 UTC, guewen commented
Thanks a lot!

2016-12-02 11:39 UTC, merged

2016-12-05 07:44 UTC, guewen commented
Tests are failing